# Generated by Django 4.1.3 on 2022-12-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_tab03'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
