# Generated by Django 4.1.3 on 2023-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_tab04'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab04',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
